# Generated by Django 3.0.4 on 2020-03-19 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medvinapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
